package com.frostox.doughnuts.dbase;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.frostox.doughnuts.dbase.Key;

import com.frostox.doughnuts.dbase.KeyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig keyDaoConfig;

    private final KeyDao keyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        keyDaoConfig = daoConfigMap.get(KeyDao.class).clone();
        keyDaoConfig.initIdentityScope(type);

        keyDao = new KeyDao(keyDaoConfig, this);

        registerDao(Key.class, keyDao);
    }
    
    public void clear() {
        keyDaoConfig.getIdentityScope().clear();
    }

    public KeyDao getKeyDao() {
        return keyDao;
    }

}
