package com.frostox.doughnuts.dbase;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table KEY.
 */
public class Key {

    private Long id;
    /** Not-null value. */
    private String name;
    private Short value;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Key() {
    }

    public Key(Long id) {
        this.id = id;
    }

    public Key(Long id, String name, Short value) {
        this.id = id;
        this.name = name;
        this.value = value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Short getValue() {
        return value;
    }

    public void setValue(Short value) {
        this.value = value;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
