package com.frostox.doughnuts.dbase;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table KEY.
 */
public class Key {

    private Long id;
    /** Not-null value. */
    private String access;
    /** Not-null value. */
    private String refresh;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Key() {
    }

    public Key(Long id) {
        this.id = id;
    }

    public Key(Long id, String access, String refresh) {
        this.id = id;
        this.access = access;
        this.refresh = refresh;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getAccess() {
        return access;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccess(String access) {
        this.access = access;
    }

    /** Not-null value. */
    public String getRefresh() {
        return refresh;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRefresh(String refresh) {
        this.refresh = refresh;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
